name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-ci:
    uses: ./.github/workflows/reuseble-python-ci.yml
    with:
      python-version: "3.12"
      requirements-file: "requirements.txt"
